Print missing packages on error.
Incorporated suggested changes in #72

diff --git a/melpa b/melpa
--- a/melpa
+++ b/melpa
@@ -36,6 +36,17 @@ function melpa_validate {
     NUMBUILT=$(trim `ls packages/*.{el,tar} | wc -l`)
 
     echo "${NUMBUILT}/${NUMPACKAGES} packages built"
+
+    if [[ $NUMBUILT -ne $NUMPACKAGES ]]; then
+        echo
+        echo "Missing Packages"
+        echo "______________________"
+        emacs --script missing.el
+        exit 1
+    else
+        exit 0
+    fi
+
 }
 
 function print_usage {
